# Generated by Django 5.1.1 on 2024-10-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0003_remove_cliente_importe_remove_pago_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
