# Generated by Django 5.1.1 on 2024-10-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0004_alter_pago_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='importe_pagado',
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
